### PR TITLE
Not yet, tobe continued on this morning

### PR DESCRIPTION
**Pull request by ghost**
Not done yet.
I felt sleepy and can't working anymore.
I will fix it in morning.

### CODE REVIEW

**Comment by kietnguyen711998** [comment]
Yep bro @@

**Comment by kietnguyen711998** [comment]
There are so many problems, right ...? ^ ^

**Comment by ghost** [comment]
> There are so many problems, right ...? ^ ^

I'm fixing right now.
You still need that?

**Comment by kietnguyen711998** [comment]
Yeah !!! I haven't done that yet, so it's hard for me to work for the first time ...

**Comment by kietnguyen711998** [comment]
Yo bro !!!  Are there many problems in the project?  You can send your project current copy to me for editing together @@

**Comment by kietnguyen711998** [comment]
Bro , it's already afternoon, what's the problem with the project ? Looking forward to your reply ...

**Comment by ghost** [comment]
> Bro , it's already afternoon, what's the problem with the project ? Looking forward to your reply ...

I forgot about it, i'm came to company late and too busy on this morning.
I'm coding... don't worry

**Comment by kietnguyen711998** [comment]
Well ! No problem ... Hope you help me finish the project soon . Thanks @@

**Comment by kietnguyen711998** [comment]
hey my friend, I'll be back 5 o'clock and I don't know how far you're done
 ???  :))

**Comment by kietnguyen711998** [comment]
Bro , there is something wrong with my project, why can't I transfer it and I can just transfer it normally
So Sad !!!

**Comment by kietnguyen711998** [comment]
How long will you be there if you don't return home? Can I finish your project at home? Not sure if you have to go to QN or in Danang .  I'll come 5.45 p.m o'clock. @@

**Comment by kietnguyen711998** [comment]
Bro !!! How's this going ^ ^

**Comment by kietnguyen711998** [comment]
Bro Everything OK

**Pull request merged**
